package alertSystemSMS.notificationMicroservice.repository;

import alertSystemSMS.notificationMicroservice.model.UserPreferenceAlertType;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Spring Data JPA repository for the UserPreferenceAlertType entity.
 * Note that the primary key type is the composite key class, UserPreferencePK.
 */
@Repository
public interface UserPreferenceAlertTypeRepository extends JpaRepository<UserPreferenceAlertType, UserPreferenceAlertType.UserPreferencePK> {
    /**
     * Finds all user preferences for a given alert type where the preference is enabled.
     * This query is automatically generated by Spring Data JPA from the method name.
     * It will find all users who have subscribed to a specific alert.
     */
    List<UserPreferenceAlertType> findByAlertType_AlertIdAndIsEnabledTrue(Long alertId);
}